extends Node
## AUTO-GENERATED by v_Godot/tools/gen_missions.py from build_game.py
## MISSION_DEFS + MISSION_REQUIRED_CAR. Do not hand-edit; re-run the extractor.
##  25 missions.

const MISSION_DEFS := [
 {
  "id": "visit_planet",
  "name": "Visit a 2nd planet",
  "details": "",
  "reward": 1000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "select_planet",
    "text": "CLICK on a nearby planet with a STATION to select it"
   },
   {
    "id": "click_route_btn",
    "text": "Then CLICK on \"ROUTE TRAIN HERE\" in the bottom panel"
   },
   {
    "id": "click_train",
    "text": "Then CLICK on a TRAIN to send on a ONE-WAY ROUTE to that planet"
   },
   {
    "id": "await_arrival",
    "text": "WAIT for your TRAIN to LOAD cargo, depart orbit, and transit to another planet"
   }
  ]
 },
 {
  "id": "create_route",
  "name": "Create a 3-planet train route",
  "details": "",
  "reward": 2000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "sel_lava_start",
    "text": "CLICK on the LAVA PLANET (or a TRAIN orbiting that planet) to select a starting point for your ROUTE"
   },
   {
    "id": "shift_orijen",
    "text": "SHIFT+CLICK on ORIJEN (your HOME PLANET) to ADD A STOP to your route"
   },
   {
    "id": "shift_desert",
    "text": "SHIFT+CLICK on the DESERT PLANET to ADD ANOTHER STOP to your route"
   },
   {
    "id": "shift_loop",
    "text": "SHIFT+CLICK on the LAVA PLANET to complete the LOOP ROUTE"
   },
   {
    "id": "assign_route",
    "text": "ASSIGN this ROUTE to a TRAIN"
   }
  ]
 },
 {
  "id": "buy_second_train",
  "name": "Buy an Iron-delivery Train",
  "details": "",
  "reward": 15000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "open_trains",
    "text": "Press \"T\" to open the \"Trains\" window"
   },
   {
    "id": "open_builder",
    "text": "Press the \"+\" sign to open the Train Builder"
   },
   {
    "id": "purchase_train",
    "text": "Purchase a new train with 2+ [Iron] cars"
   },
   {
    "id": "deliver_iron_orijen",
    "text": "Using your new TRAIN, load [Iron] from the DESERT PLANET and deliver it to ORIJEN"
   }
  ]
 },
 {
  "id": "produce_iron",
  "name": "Produce Iron",
  "details": "Put your new foundry to work smelting raw ore into refined iron.",
  "reward": 10000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "build_foundry",
  "objectives": [
   {
    "id": "deliver_ore_water",
    "text": "Deliver both [Molten Ore] and [Water] to a DESERT PLANET with a FOUNDRY"
   },
   {
    "id": "wait_smelt",
    "text": "Wait 40 seconds for the FOUNDRY to SMELT IRON"
   }
  ]
 },
 {
  "id": "upgrade_station",
  "name": "Upgrade a Station",
  "details": "STATIONS only allow one train (in LOW ORBIT) to load or unload at a time, while a LARGE STATION can accommodate trains in two orbits.",
  "reward": 50000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "produce_iron",
  "objectives": [
   {
    "id": "deliver_4_iron_for_upgrade",
    "text": "Deliver 4 [Iron] to a planet with a STATION you\u2019d like to upgrade"
   },
   {
    "id": "upgrade_to_large_station",
    "text": "Upgrade a STATION to a LARGE STATION"
   }
  ]
 },
 {
  "id": "design_better_train",
  "name": "Designing a better space train",
  "details": "Scientists on {TARGET} are prototyping a new space train engine, and they need materials from nearby planets",
  "reward": null,
  "reward_text": "A new engine type",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_10_steel_home",
    "text": "Deliver 20 [Steel] to {TARGET}"
   },
   {
    "id": "deliver_10_battery_home",
    "text": "Deliver 20 [Battery] to {TARGET}"
   },
   {
    "id": "deliver_10_oil_home",
    "text": "Deliver 20 [Oil] to {TARGET}"
   }
  ]
 },
 {
  "id": "build_foundry",
  "name": "Build a Foundry",
  "details": "Establish a foundry to smelt molten ore into refined iron.",
  "reward": 10000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "station_foundry_planet",
    "text": "Construct a STATION on a DESERT PLANET"
   },
   {
    "id": "construct_foundry",
    "text": "Construct a FOUNDRY on a DESERT PLANET"
   }
  ]
 },
 {
  "id": "dispose_hazmat",
  "name": "Dispose of Hazmat",
  "details": "Industrial activity produces Hazmat as a by-product. As Hazmat accumulates on a planet, it drags down the planet's productivity & its people's happiness. Pick up Hazmat from a planet with Hazmat cars & transport it to the nearest star for incineration.",
  "reward": 8000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "incinerate_hazmat",
    "text": "Incinerate 2.0 units of [Hazmat]"
   }
  ]
 },
 {
  "id": "lost_colony",
  "name": "Lost Colony",
  "details": "The ancient alien relics left on this planet contain a map to another planet... Could others still be alive?",
  "reward": 15000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "visit_relic_target",
    "text": "Use the map you've found to locate another planet from this alien civilization"
   }
  ]
 },
 {
  "id": "seeking_home",
  "name": "Seeking a Way Home",
  "details": "",
  "reward": 100000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "rocky_home",
    "text": "Help Rocky back to his home planet, by transporting 1 unit of [Passengers] from {SOURCE} to {TARGET}"
   }
  ]
 },
 {
  "id": "spread_the_seed",
  "name": "Spread the Seed",
  "details": "",
  "reward": 88888,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_flowers_10",
    "text": "Deliver [Flowers] to 10+ planets capable of growing them (Jungle, Desert, or Resort)"
   }
  ]
 },
 {
  "id": "research_royal_car",
  "name": "Researching a better passenger car",
  "details": "",
  "reward": null,
  "reward_text": "A new type of train car",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_50_to_origen",
    "text": "Deliver 50 units of passenger cargo to {TARGET}"
   }
  ]
 },
 {
  "id": "famine",
  "name": "Famine",
  "details": "",
  "reward": 200000,
  "reward_text": "",
  "time_limit": 2.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_20_livestock",
    "text": "Deliver 10 units of food ([Livestock]) to {TARGET} within 2.0 stardates"
   }
  ]
 },
 {
  "id": "colony_train",
  "name": "Colony Train",
  "details": "",
  "reward": 100000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "build_station",
    "text": "Build a Station on {SOURCE}"
   },
   {
    "id": "bring_10_pax",
    "text": "Bring a train with 10 passenger cars to {SOURCE} to pick up Reza Mansoor and the rest of his colony"
   },
   {
    "id": "deliver_colonists",
    "text": "Deliver the colonists to {TARGET}"
   }
  ]
 },
 {
  "id": "outbreak",
  "name": "Outbreak",
  "details": "",
  "reward": 500,
  "reward_text": "",
  "time_limit": 1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_4_medical",
    "text": "Deliver 4 units of [Medical] supplies to {TARGET} within 1.0 stardate"
   }
  ]
 },
 {
  "id": "stellar_cartography",
  "name": "Stellar Map Cartography",
  "details": "",
  "reward": 50000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "visit_5_systems",
    "text": "Visit a planet in 5 separate star systems"
   }
  ]
 },
 {
  "id": "sandstorm_relief",
  "name": "Sand Storm Relief",
  "details": "",
  "reward": 20000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_10_sand",
    "text": "Load and remove 10 units of [Sand] from {SOURCE} by delivering it anywhere"
   }
  ]
 },
 {
  "id": "galactic_distance",
  "name": "Galactic Distance Record",
  "details": "",
  "reward": 30000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_15k_au",
    "text": "Deliver any cargo or passengers on a single trip of more than 15,000 SU"
   }
  ]
 },
 {
  "id": "galaxy_census",
  "name": "Galaxy Census",
  "details": "",
  "reward": null,
  "reward_text": "Sensor Upgrade",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "visit_50_planets",
    "text": "Visit 50 or more planets across the galaxy"
   }
  ]
 },
 {
  "id": "corporate_expansion",
  "name": "Corporate Expansion",
  "details": "",
  "reward": null,
  "reward_text": "\u221210% Station Cost",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "stations_7",
    "text": "Build stations on 7 or more planets"
   },
   {
    "id": "trains_profitable_1sd",
    "text": "Have 5 or more trains whose revenue exceeded maintenance costs within the last 1 S.D."
   }
  ]
 },
 {
  "id": "bh_research",
  "name": "Black Hole Research",
  "details": "",
  "reward": 150000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_5_chemical",
    "text": "Deliver 5 units of [Chemical] cargo to the research station at {TARGET}"
   }
  ]
 },
 {
  "id": "mad_scientist",
  "name": "A Mad Scientist",
  "details": "",
  "reward": null,
  "reward_text": "A new engine type",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "pickup_scientist",
    "text": "Send a TRAIN equipped with a [Passenger Car] to pick up the Mad Scientist (1 unit of [Passengers]) from {SOURCE}"
   },
   {
    "id": "deliver_scientist",
    "text": "Deliver the Mad Scientist back to ORIJEN"
   }
  ]
 },
 {
  "id": "ancient_schematics",
  "name": "Ancient Schematics",
  "details": "",
  "reward": 10000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "deliver_schematics",
    "text": "Deliver the Ancient Schematics (1 unit of [Cargo]) from {SOURCE} back to ORIJEN so your best scientists can help to decipher these ancient scripts"
   }
  ]
 },
 {
  "id": "another_dimension",
  "name": "Another Dimension?",
  "details": "",
  "reward": null,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "wait_research",
    "text": "Wait for scientists to finish their research"
   }
  ]
 },
 {
  "id": "more_scientists",
  "name": "More scientists needed!",
  "details": "",
  "reward": 250000,
  "reward_text": "",
  "time_limit": -1.0,
  "prerequisite": "",
  "objectives": [
   {
    "id": "sci_urban",
    "text": "Pick up a scientist (1 unit of [Passengers]) from {SCI1} and deliver them to the research outpost at {TARGET}"
   },
   {
    "id": "sci_oil",
    "text": "Pick up a scientist (1 unit of [Passengers]) from {SCI2} and deliver them to the research outpost at {TARGET}"
   },
   {
    "id": "sci_storm",
    "text": "Pick up a scientist (1 unit of [Passengers]) from {SCI3} and deliver them to the research outpost at {TARGET}"
   }
  ]
 }
]

const MISSION_REQUIRED_CAR := {
 "dispose_hazmat": "car_hazmat",
 "spread_the_seed": "car_flowers",
 "famine": "car_livestock",
 "outbreak": "car_medical",
 "sandstorm_relief": "car_sand",
 "bh_research": "car_chemical",
 "ancient_schematics": "car_cargo"
}
