#!/usr/bin/env python3
"""Extract MISSION_DEFS + _MISSION_REQUIRED_CAR from build_game.py into GDScript
const blocks (faithful data port for v_Godot Missions.gd). JSON literals are
valid GDScript for dict/array/string/number/null, so we emit JSON directly.

Usage: python -X utf8 gen_missions.py  > ../space-train-tycoon/autoload/_mission_data.gd
"""
import re, json, sys, os

SRC = os.path.join(os.path.dirname(__file__), "..", "..", "build_game.py")
text = open(SRC, encoding="utf-8").read()
lines = text.splitlines()

# --- MISSION_DEFS region: from `const MISSION_DEFS=[` to the matching `];` ---
start = next(i for i, l in enumerate(lines) if re.match(r"\s*const MISSION_DEFS\s*=\s*\[", l))
end = next(i for i in range(start + 1, len(lines)) if re.match(r"\];", lines[i]))
region = "\n".join(lines[start + 1:end])

# Split into top-level mission blocks: each begins at a 2-space-indented `{id:`.
block_starts = [m.start() for m in re.finditer(r"(?m)^  \{id:", region)]
blocks = []
for k, s in enumerate(block_starts):
    e = block_starts[k + 1] if k + 1 < len(block_starts) else len(region)
    blocks.append(region[s:e])

def unq(s):
    return s.replace("\\'", "'").replace('\\"', '"').replace("\\\\", "\\")

def field(block, name, default=None):
    m = re.search(name + r":\s*'((?:[^'\\]|\\.)*)'", block)
    if m:
        return unq(m.group(1))
    return default

def num_field(block, name):
    m = re.search(name + r":\s*(null|-?[\d.]+)", block)
    if not m:
        return None
    v = m.group(1)
    return None if v == "null" else (float(v) if "." in v else int(v))

missions = []
for b in blocks:
    mid = field(b, "id")
    name = field(b, "name", "")
    details = field(b, "details", "")
    reward = num_field(b, "reward")
    reward_text = field(b, "rewardText", "")
    time_limit = num_field(b, "timeLimit")
    prereq = field(b, "prerequisite", "")
    objs = []
    om = re.search(r"objectives:\s*\[(.*?)\]\s*,", b, re.S)
    if om:
        for o in re.finditer(r"\{id:\s*'([^']+)',\s*text:\s*'((?:[^'\\]|\\.)*)'\s*\}", om.group(1), re.S):
            objs.append({"id": o.group(1), "text": unq(o.group(2))})
    missions.append({
        "id": mid, "name": name, "details": details,
        "reward": reward, "reward_text": reward_text,
        "time_limit": time_limit if time_limit is not None else -1.0,
        "prerequisite": prereq or "",
        "objectives": objs,
    })

# --- _MISSION_REQUIRED_CAR map ---
rc = {}
rcm = re.search(r"const _MISSION_REQUIRED_CAR\s*=\s*\{(.*?)\};", text, re.S)
if rcm:
    for m in re.finditer(r"(\w+):\s*'([^']+)'", rcm.group(1)):
        rc[m.group(1)] = m.group(2)

print("extends Node")
print("## AUTO-GENERATED by v_Godot/tools/gen_missions.py from build_game.py")
print("## MISSION_DEFS + MISSION_REQUIRED_CAR. Do not hand-edit; re-run the extractor.")
print("##  %d missions." % len(missions))
print()
print("const MISSION_DEFS := " + json.dumps(missions, indent=1))
print()
print("const MISSION_REQUIRED_CAR := " + json.dumps(rc, indent=1))
sys.stderr.write("Extracted %d missions, %d car-gates.\n" % (len(missions), len(rc)))
